### PR TITLE
Azure active directory

### PR DESCRIPTION
**Pull request by grovecj**
All API requests (except OPTIONS) require a valid, signed access token in the Authorization header.

Requests can be authorized based on group memberships at the method or controller level using the annotations `@PreAuthorize` or `@PostAuthorize`. An example of this can be found commented out at the top of `ReportController`.

>Note that this is currently not compatible with the master branch of the budget-tracker-ui repository--all requests will 401. You can comment out lines 22 and 23 in `SecurityConfig` to bypass the authentication mechanism.

### CODE REVIEW

**Comment by grovecj** [comment]
Corresponds to [this PR](https://github.com/allegient-labs/budget-tracker-ui/pull/9) in the front end.

**Comment by jrgarlick** [comment]
Hey Carter, Is this ready to merge? I noticed your comment about how everything produces 401 errors. What do we need to do to authenticate? Thanks.

**Comment by grovecj** [comment]
I believe that this feature is complete and ready to merge. All I meant by that comment is that the front end app will not be able to make requests against the back end without sending a proper access token. There is a pull request open in the front end repository that implements this, but it hasn't been merged in yet.

**Review by jrgarlick — APPROVED** [review]
You're gonna have to show me how this works  ;)

**Pull request merged**
